// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'wish_list.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

WishList _$WishListFromJson(Map<String, dynamic> json) => WishList(
      id: json['id'] as String?,
      name: json['name'] as String?,
      canAddAllToCart: json['canAddAllToCart'] as bool?,
      description: json['description'] as String?,
      updatedOn: json['updatedOn'] == null
          ? null
          : DateTime.parse(json['updatedOn'] as String),
      updatedByDisplayName: json['updatedByDisplayName'] as String?,
      wishListLinesCount: (json['wishListLinesCount'] as num?)?.toInt(),
      wishListSharesCount: (json['wishListSharesCount'] as num?)?.toInt(),
      isSharedList: json['isSharedList'] as bool?,
      sharedByDisplayName: json['sharedByDisplayName'] as String?,
      pagination: json['pagination'] == null
          ? null
          : Pagination.fromJson(json['pagination'] as Map<String, dynamic>),
      wishListLineCollection: (json['wishListLineCollection'] as List<dynamic>?)
          ?.map((e) => WishListLine.fromJson(e as Map<String, dynamic>))
          .toList(),
      allowEditingBySharedWithUsers: json['allowEdit'] as bool?,
      shareOption: json['shareOption'] as String?,
      isAutogenerated: json['isAutogenerated'] as bool?,
      isFavorite: json['isFavorite'] as bool?,
      wishListTags: (json['wishListTags'] as List<dynamic>?)
          ?.map((e) => WishListTagModel.fromJson(e as Map<String, dynamic>))
          .toList(),
    )
      ..uri = json['uri'] as String?
      ..properties = (json['properties'] as Map<String, dynamic>?)?.map(
        (k, e) => MapEntry(k, e as String?),
      );

Map<String, dynamic> _$WishListToJson(WishList instance) => <String, dynamic>{
      if (instance.uri case final value?) 'uri': value,
      if (instance.properties case final value?) 'properties': value,
      if (instance.id case final value?) 'id': value,
      if (instance.name case final value?) 'name': value,
      if (instance.canAddAllToCart case final value?) 'canAddAllToCart': value,
      if (instance.description case final value?) 'description': value,
      if (instance.updatedOn?.toIso8601String() case final value?)
        'updatedOn': value,
      if (instance.updatedByDisplayName case final value?)
        'updatedByDisplayName': value,
      if (instance.wishListLinesCount case final value?)
        'wishListLinesCount': value,
      if (instance.wishListSharesCount case final value?)
        'wishListSharesCount': value,
      if (instance.isSharedList case final value?) 'isSharedList': value,
      if (instance.sharedByDisplayName case final value?)
        'sharedByDisplayName': value,
      if (instance.pagination?.toJson() case final value?) 'pagination': value,
      if (instance.wishListLineCollection?.map((e) => e.toJson()).toList()
          case final value?)
        'wishListLineCollection': value,
      if (instance.allowEditingBySharedWithUsers case final value?)
        'allowEdit': value,
      if (instance.shareOption case final value?) 'shareOption': value,
      if (instance.isAutogenerated case final value?) 'isAutogenerated': value,
      if (instance.isFavorite case final value?) 'isFavorite': value,
      if (instance.wishListTags?.map((e) => e.toJson()).toList()
          case final value?)
        'wishListTags': value,
    };
