import 'models.dart';

part 'wish_list.g.dart';

@JsonSerializable()
class WishList extends BaseModel {
  String? id;

  String? name;

  bool? canAddAllToCart;

  String? description;

  DateTime? updatedOn;

  String? updatedByDisplayName;

  int? wishListLinesCount;

  int? wishListSharesCount;

  bool? isSharedList;

  String? sharedByDisplayName;

  Pagination? pagination;

  List<WishListLine>? wishListLineCollection;

  @JsonKey(name: "allowEdit")
  bool? allowEditingBySharedWithUsers;

  String? shareOption;

  bool? isAutogenerated;

  bool? isFavorite;

  List<WishListTagModel>? wishListTags;

  WishList({
    this.id,
    this.name,
    this.canAddAllToCart,
    this.description,
    this.updatedOn,
    this.updatedByDisplayName,
    this.wishListLinesCount,
    this.wishListSharesCount,
    this.isSharedList,
    this.sharedByDisplayName,
    this.pagination,
    this.wishListLineCollection,
    this.allowEditingBySharedWithUsers,
    this.shareOption,
    this.isAutogenerated,
    this.isFavorite,
    this.wishListTags,
  });

  factory WishList.fromJson(Map<String, dynamic> json) =>
      _$WishListFromJson(json);

  Map<String, dynamic> toJson() => _$WishListToJson(this);
}
