// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'wish_list.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

WishList _$WishListFromJson(Map<String, dynamic> json) => WishList(
      id: json['id'] as String?,
      name: json['name'] as String?,
      canAddAllToCart: json['canAddAllToCart'] as bool?,
      description: json['description'] as String?,
      updatedOn: json['updatedOn'] == null
          ? null
          : DateTime.parse(json['updatedOn'] as String),
      updatedByDisplayName: json['updatedByDisplayName'] as String?,
      wishListLinesCount: (json['wishListLinesCount'] as num?)?.toInt(),
      wishListSharesCount: (json['wishListSharesCount'] as num?)?.toInt(),
      isSharedList: json['isSharedList'] as bool?,
      sharedByDisplayName: json['sharedByDisplayName'] as String?,
      pagination: json['pagination'] == null
          ? null
          : Pagination.fromJson(json['pagination'] as Map<String, dynamic>),
      wishListLineCollection: (json['wishListLineCollection'] as List<dynamic>?)
          ?.map((e) => WishListLine.fromJson(e as Map<String, dynamic>))
          .toList(),
      allowEditingBySharedWithUsers: json['allowEdit'] as bool?,
      shareOption: json['shareOption'] as String?,
      isAutogenerated: json['isAutogenerated'] as bool?,
      isFavorite: json['isFavorite'] as bool?,
      wishListTags: (json['wishListTags'] as List<dynamic>?)
          ?.map((e) => WishListTagModel.fromJson(e as Map<String, dynamic>))
          .toList(),
    )
      ..uri = json['uri'] as String?
      ..properties = (json['properties'] as Map<String, dynamic>?)?.map(
        (k, e) => MapEntry(k, e as String?),
      );

Map<String, dynamic> _$WishListToJson(WishList instance) {
  final val = <String, dynamic>{};

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('uri', instance.uri);
  writeNotNull('properties', instance.properties);
  writeNotNull('id', instance.id);
  writeNotNull('name', instance.name);
  writeNotNull('canAddAllToCart', instance.canAddAllToCart);
  writeNotNull('description', instance.description);
  writeNotNull('updatedOn', instance.updatedOn?.toIso8601String());
  writeNotNull('updatedByDisplayName', instance.updatedByDisplayName);
  writeNotNull('wishListLinesCount', instance.wishListLinesCount);
  writeNotNull('wishListSharesCount', instance.wishListSharesCount);
  writeNotNull('isSharedList', instance.isSharedList);
  writeNotNull('sharedByDisplayName', instance.sharedByDisplayName);
  writeNotNull('pagination', instance.pagination?.toJson());
  writeNotNull('wishListLineCollection',
      instance.wishListLineCollection?.map((e) => e.toJson()).toList());
  writeNotNull('allowEdit', instance.allowEditingBySharedWithUsers);
  writeNotNull('shareOption', instance.shareOption);
  writeNotNull('isAutogenerated', instance.isAutogenerated);
  writeNotNull('isFavorite', instance.isFavorite);
  writeNotNull(
      'wishListTags', instance.wishListTags?.map((e) => e.toJson()).toList());
  return val;
}
