name: commerce_flutter_sdk
description: A new Flutter project.
publish_to: "none"
version: 4.5.1+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: 3.32.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  url_launcher: ^6.1.12
  map_launcher: ^3.2.0
  optimizely_commerce_api:
    path: ./commerce-dart-sdk
  shared_preferences: ^2.2.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  flutter_widget_from_html: ^0.16.0
  loading_animation_widget: ^1.3.0
  device_info_plus: ^11.4.0
  local_auth: ^2.2.0
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
  intl: ^0.20.2
  badges: ^3.1.2
  flutter_secure_storage: ^10.0.0-beta.4
  package_info_plus: ^8.1.2
  google_mlkit_barcode_scanning: ^0.14.1
  camera: ^0.10.6
  image: ^4.1.7
  collection: ^1.18.0
  firebase_core: 4.0.0
  firebase_crashlytics: ^5.0.0
  connectivity_plus: ^6.1.1
  google_maps_flutter: ^2.6.1
  latlong2: ^0.9.1
  location: ^8.0.0
  firebase_remote_config: 6.0.0
  firebase_analytics: 12.0.0
  appcenter_analytics:
    path: ./appcenter_analytics
  json_annotation: ^4.9.0
  flutter_staggered_grid_view: ^0.7.0
  bloc_concurrency: ^0.3.0
  firebase_messaging: 16.0.0
  flutter_local_notifications: 19.3.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.24.1
  mocktail: ^1.0.2
  bloc_test: ^10.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/bar_icons/
    - assets/images/cart_page_icons/
    - assets/images/biometric_icons/
    - assets/images/checkout_icons/
    - assets/images/wish_list_icons/
    - assets/config/
    - assets/form/
