name: commerce_flutter_sdk
description: A new Flutter project.
publish_to: "none"
version: 4.3.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: 3.27.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  go_router: ^13.2.0
  google_fonts: 6.1.0
  url_launcher: ^6.1.12
  map_launcher: ^3.2.0
  optimizely_commerce_api:
    path: ./commerce-dart-sdk
  shared_preferences: ^2.2.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  flutter_widget_from_html: ^0.15.3
  loading_animation_widget: ^1.3.0
  device_info_plus: ^9.1.2
  local_auth: ^2.2.0
  webview_flutter: 4.10.0
  webview_flutter_android: 4.3.3
  intl: ^0.18.1
  badges: ^3.1.2
  flutter_secure_storage: ^9.0.0
  package_info_plus: ^8.1.2
  google_mlkit_barcode_scanning: 0.13.0
  camera: 0.10.6
  image: ^4.1.7
  collection: ^1.18.0
  firebase_core: 3.9.0
  firebase_crashlytics: 4.2.0
  connectivity_plus: ^6.1.1
  google_maps_flutter: ^2.6.1
  latlong2: ^0.9.1
  location: ^6.0.2
  firebase_remote_config: 5.0.3
  firebase_analytics: 11.2.0
  appcenter_analytics:
    path: ./appcenter_analytics
  json_annotation: ^4.9.0
  flutter_staggered_grid_view: ^0.7.0
  bloc_concurrency: ^0.2.5
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^19.3.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.1
  mocktail: ^1.0.2
  bloc_test: ^9.1.5
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/bar_icons/
    - assets/images/cart_page_icons/
    - assets/images/biometric_icons/
    - assets/images/checkout_icons/
    - assets/images/wish_list_icons/
    - assets/config/
    - assets/form/
